### ISSUE TITLE
YuMiArm close_gripper() function has multiple missing parameters

### ISSUE THREAD

**Issue by jeffmahler** [BerkeleyAutomation/yumipy#1]
force and width are checked but not passed in to the constructor

**Comment by jacky-liang** [comment]
Fixed by [70e5073](https://github.com/BerkeleyAutomation/yumipy/commit/70e50737561967dd74fce5ebe674cf25434f8be0) and [f9a0add](https://github.com/BerkeleyAutomation/yumipy/commit/f9a0add56b9f2eea0b88021cd39545a331888016)
