### ISSUE TITLE
YuMi Arm-angle Definition/Robtargets Issue

### ISSUE THREAD

**Issue by TAS104** [BerkeleyAutomation/yumipy#12]
Hello,
I tried using the example code given in the installation instructions on the wiki in a ROS package:

_from_ yumipy import YuMiRobot
_**start the robot interface**_
_y = YuMiRobot(arm_type='remote')_
_**getting the current pose of the right end effector**_
_pose = y.right.get_pose()_
_**move right arm forward by 5cm using goto_pose**_
_pose.translation[0] += 0.05_
_y.right.goto_pose(pose)_
_**move right arm back by 5cm using move delta**_
_y.right.goto_pose_delta((-0.05,0,0))__

The program ran but I received the following error message on the FlexPendant for the YuMi robot:

_Event Message 50488
Using old target definition
Description
The target for ROB_R is using the old definition for cfx.
This is not compatible with the new arm angle definition.
Actions
Convert robtargets in the RAPID program to the new arm-angle definition (recommended) or change the configuration parameter Arm-Angle definition topic Motion and type Robot to ‘Old’._

How should this change be made, is it possible to change this arm-angle definition using a conversion in the ROS code or is this something that has to be changed in the RAPID server?

**Comment by jeffmahler** [comment]
Interesting, we have not seen this error before. I suspect that you are on a new version of RobotWare that changed the target definitions. What is your version? We are on 6.03.00.00.

**Comment by TAS104** [comment]
The RobotWare version running on the YuMi robot is 6.04.01.00.

**Comment by jeffmahler** [comment]
After a bit of searching, I recommend changing the parameter "Arm-Angle Definition" from "New" to "Old" as described [here](https://forums.robotstudio.com/discussion/10324/how-to-set-yumis-configuration-when-using-move-instruction).

It seems that you can do this by navigating on the FlexPendant to "Control Panel"->"Configuration"->"Topics"->"Motion"->"Robot" and then clicking on the parameter.

**Comment by TAS104** [comment]
Thank you for the advice, this solution has worked and we could control the robot with ROS. Whilst using the code mentioned in the first post of this thread we were successfully able to use the move delta command however we encountered errors with the commands relating to getting the current pose of the robot arm, applying a translation and moving the arm to the new position. These errors seemed to indicate that the pose used with the goto_pose was unreachable by the robot.

To ensure the requested pose was reachable, we modified the above code so that the current pose of the robot would be saved and printed to the computer screen, move delta would be used to move the arm forward 10 cm and goto_pose used to move back to the original pose. Every time we tried to move the robot back to its original pose using this sequence of commands we got the following errors:

_Traceback (most recent call last):_
  _File "/home/ezzdtb/YuMi_CAM_ws/src/yumitest/src/test.py", line 22, in <module>
    y.right.goto_pose(pose)_
  _File "/home/ezzdtb/YuMi_CAM_ws/src/yumipy/./yumipy/yumi_arm.py", line 1184, in handle_remote_call
    raise RuntimeError("Service call failed: {0}".format(str(e)))_
_RuntimeError: Service call failed: service [/yumi_robot/right_arm] responded with an error: error processing request: Failed Request!_
_Req: _REQ_PACKET(req='1 229.1 -334.4 176 -0.06499 0.65488 0.06799 0.74986 #', timeout=8, return_res=True)_
_Res: _RAW_RES(mirror_code=1, res_code=0, message='Unreachable Pose')_

This seems to indicate that the error is due to an unreachable pose however the pose requested should be within the robot's reach. The only difference between the position printed and that displayed on the FlexPendant was that the signs on each of the values of the Quaternion were the opposite i.e. one being negative where the other gives positive with the same absolute value however I don't think this would make a difference.

**Comment by jacky-liang** [comment]
YuMi's motion planner sometimes acts in unintuitive ways. It is rarely this case but it is possible to perform for the YuMi to go to a pose from a starting pose w/o any errors but triggering an unreachable pose error when going back to the starting pose.

To help us debug, could you:
- Paste the exact series of commands you've run to trigger this error, including the initial poses of the robot
- Try performing the movement at a different starting pose.
- Try to perform the backwards motion w/ goto_pose_delta instead of goto_pose

Note that if the optional arg "relative" is set to True in goto_pose (it defaults to False), then goto_pose will compute the relative pose and call goto_pose_delta.

**Comment by TAS104** [comment]
The exact series of commands used in this case are:

_from yumipy import YuMiRobot_

_y = YuMiRobot(arm_type='remote')
pose = y.right.get_pose()
print(pose)
y.right.goto_pose_delta((+0.10,0,0))
y.right.goto_pose(pose)_

The original position was:

Tra: [ 0.22910002 -0.33443001  0.17604001]
 Rot: [[-0.13382395  0.18651025  0.97329599]
 [-0.00841685 -0.98230862  0.18708003]
 [ 0.99096938  0.0168437   0.13302625]]
 Qtn: [-0.06498785  0.65487755  0.06798729  0.74985979]


When the move delta command was executed the position was given on the FlexPendant as:

Tra: [0.32909 -0.33444  0.17604]
Qtn: [0.06498  -0.65522  -0.06793  -0.74957]

Following the successful execution of this command the error occurred.

We tried running the robot from a few different positions before and the go to pose command did work on one occasion, however I do not have the positions for this, but otherwise kept hitting the same error.

I will try this code again for different arm positions and provide the response however I will be unable to do this until next week.

**Comment by jacky-liang** [comment]
I was able to reproduce the error with your commands, starting at the home pose of the YuMi. Unfortunately there isn't much we can do here, as YuMi's internal motion planners are not "consistent" in the sense that successfully commanding a sequence of poses one way does not guarantee that the same sequence of poses can be successfully executed in reverse. 

In contrast, a sequence of reachable joints should always be able to be executed with the same success forwards and backwards. 

For our applications we have yet to run into scenarios where YuMi's pose inconsistency became a significant problem, as it doesn't occur for most of the workspace. If it is crucial for your application that you need that specific pose for some trajectory, I'd recommend using joints for that step instead.
