### ISSUE TITLE
YuMi Coordinates & Orientation using Rigid Transform Example

### ISSUE THREAD

**Issue by TAS104** [BerkeleyAutomation/yumipy#14]
Hello,

Could you provide an example of the correct way to define a pose from scratch (without modifying a pose given by get_pose), where the gripper is pointing down at the work surface using Rigid Transform as defined in the API documentation. 

What is the best way to define accurate orientations and get each arm to move to them e.g. if the robot needs to hold an object in one gripper and manipulate it with another?

**Comment by jeffmahler** [comment]
Assuming `theta` is the orientation of the gripper in the plane of the table and `translation` is a 3-vector describing the location of the gripper, you can define a pose from scratch with:
```
from autolab_core import RigidTransform
R = np.array([[np.cos(theta), -np.sin(theta), 0],
                      [np.sin(theta),   np.cos(theta), 0],
                      [0, 0, -1]])
T = RigidTransform(rotation=R, translation=translation, from_frame='gripper', to_frame='world')
```

Sorry but I don't quite understand your second question, as the orientation would depend on what kind of manipulation you are trying to do.
