### ISSUE TITLE
ROS Kinetic Compatability

### ISSUE THREAD

**Issue by TAS104** [BerkeleyAutomation/yumipy#15]
Hello, 

Is Yumipy compatible with newer versions of ROS such as Kinetic since your website states it has only been tested with ROS Jade? Since Ubuntu 14.04 reaches end of life in April 2019 I will be unable to use this with ROS Jade and will have to upgrade to Ubuntu 16.04 with ROS Kinetic.

**Comment by 01halibut** [comment]
We haven't tested it with ROS Kinetic but it _should_ work (tentative). Yumipy does work independent of ROS though, so if you don't plan on using the ROS bits it doesn't matter.

**Comment by EtherW** [comment]
Hello，
So have you tested if using this with Kinetic ?
