### ISSUE TITLE
Using YuMi Camera with Yumipy

### ISSUE THREAD

**Issue by waupdog** [BerkeleyAutomation/yumipy#16]
Hi, I would like to know if there's any way of accessing the camera in the grippers of the yumi via yumipy? I'd like to be able to capture an image using it to then process with openCV to detect shapes in my workspace, however I see no mention of the camera usage in the API. 

Many thanks,
Jonathon

**Comment by jeffmahler** [comment]
Hi Jonathon, unfortunately YuMiPy does not support this feature as we do not have access to the cognex hand cameras in our lab.
