### ISSUE TITLE
Confusion with Position Control setup

### ISSUE THREAD

**Issue by juanluislm** [BerkeleyAutomation/yumipy#17]
Hello,

I am trying to set up the firmware to control YuMi using ROS, but the set up in the wiki is a bit confusing.

Since we want to do position control, we are using the files in the ABB_driver and Grippers folder. Part of the confusion has to do with adding scripts to the tasks:

![image](https://user-images.githubusercontent.com/4722547/37979860-883ece4c-319e-11e8-92fc-106bf6c1f48f.png)

The last three tasks are "ALL RWS tasks". Does that mean we have to set up the RWS tasks as well? even though we just want to do position control?

As for the grippers, I have a similar question.

![image](https://user-images.githubusercontent.com/4722547/37980110-26766ade-319f-11e8-8e41-4e416c18fe06.png)

The last three tasks are "ALL T_GRIP_XXX" tasks. Does that mean we have to attach the last three scripts to all of the T_GRIP tasks?

Thanks,
Juan

**Comment by jacky-liang** [comment]
Hi Juan,

I'm not sure which wiki you are referring to - the above instructions seems to be from a different YuMi control library that is not YuMiPy .

If you wish to manually set up the RAPID server for YuMiPy, you can refer to this previous [issue](https://github.com/BerkeleyAutomation/yumipy/issues/4).
