### ISSUE TITLE
YuMi Vacuum Gripper Compatibility

### ISSUE THREAD

**Issue by TAS104** [BerkeleyAutomation/yumipy#18]
Hello,

Is it possible to use the suction cup on Yumi's end effector using yumipy? Is there a tool setting for this and is it possible to activate/deactivate the suction cup within a ROS script?

**Comment by jeffmahler** [comment]
Hi, unfortunately built-in suction control is not supported at this time. We use a custom suction system that is controlled through an arduino on our YuMi and have never used the built-in suction.
