### ISSUE TITLE
Backup file is for Robotware 6.03, running Robotware 6.06

### ISSUE THREAD

**Issue by coverpage** [BerkeleyAutomation/yumipy#19]
The backup file is for Robotware 6.03 while the Yumi I'm working with is running on Robotware 6.06. There was a warning on this and when I force the restore backup file, there are errors.

Is it possible for there to be configuration for Yumi 6.06?

**Comment by jeffmahler** [comment]
Yes, but we need to create one and I am out of the lab for a few days. I will post it as soon as possible.

**Comment by coverpage** [comment]
Thanks, appreciate the help.

**Comment by coverpage** [comment]
Just following up on this. Otherwise are there instructions to manually set it up.

**Comment by jeffmahler** [comment]
@coverpage sorry I was not able to get around to this before leaving the country for ICRA. I will be back next week (June 4) and should be able to upload the backup. Feel free to bother me again if you don't see it by the end of that week.

**Comment by coverpage** [comment]
@jeffmahler Any updates on the 6.06 compatible backup file. Sorry for bugging you.

**Comment by jeffmahler** [comment]
Apologies for the delay. The RobotWare 6.06 backup is [here](https://github.com/BerkeleyAutomation/yumipy/blob/master/RAPID/Yumi_Backup_Stable_RobotWare_6.06.zip)
