### ISSUE TITLE
Problem with YumiPlanner, fails in initialization

### ISSUE THREAD

**Issue by kuobenj** [BerkeleyAutomation/yumipy#2]
`[ERROR] [1499895592.622562591]: Robot model parameter not found! Did you remap 'robot_description'?
Traceback (most recent call last):
  File "yumitest.py", line 6, in <module>
    y.right.set_motion_planner(YuMiMotionPlanner(arm='right'))
  File "/home/benjaminkuo/catkin_ws/src/yumipy/./yumipy/yumi_planner.py", line 36, in __init__
    self._init_planning_interface()
  File "/home/benjaminkuo/catkin_ws/src/yumipy/./yumipy/yumi_planner.py", line 42, in _init_planning_interface
    self._robot_comm = moveit_commander.RobotCommander()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/moveit_commander/robot.py", line 148, in __init__
    self._r = _moveit_robot_interface.RobotInterface(robot_description)
RuntimeError: RobotInterfacePython: invalid robot model`

I get this error message when wanting to use the Planner. The robot description is clearly never loaded in the provided lauch file. I couldn't find the robot meshes and urdfs in this repo, so I'm assuming there was more code and resources in place to get this planner up and running? If I could get some guidance on how to get this up and running that'd be great!

**Comment by jacky-liang** [comment]
Hi!
The yumi_arms launch file is for spinning up a ROS service so YuMiRobot can be instantiated and used on remote machines in the same ROS network. See [here](https://berkeleyautomation.github.io/yumipy/install/install.html#start-the-arms-service-ros-installation-only). It's not related to running the MoveIt! client-side motion planner.

In our projects although we've experimented w/ using MoveIt! to do motion planning own we often found that it is much slower than YuMi's native RAPID planners and it's difficult to enforce linear path constraints, which RAPID does fairly well. So for the most part we've been relying on YuMi's own motion planner by directly sending target poses using the YuMiRobot object.

If for your specific application you find using MoveIt! valuable, this [package](https://github.com/OrebroUniversity/yumi) contains URDF files and MoveIt! integration that you might find helpful.
