### ISSUE TITLE
Issues with running RAPID code.

### ISSUE THREAD

**Issue by Serafadam** [BerkeleyAutomation/yumipy#22]
Hi, 
I've been trying to run the code that is available on this repository, and I've run into a few issues, maybe they are on my side, but since I am new to programming this robot, some help would be appreciated. When I export rapid modules as in  #4 from the basic folder, they are exported normally, but when I loaded the library, and tried to move the robot by a centimeter, I get error from controller telling me that I am using old definition for cfx and this is not compatible with new arm angle definition (as per #12 ).
I noticed that there is a new backup from version 6.06, but when I try to load it as per instructions, I get following error:
`The type name 'ETHERNETIP_INTERNAL_ANYBUS_DEVICE' in configuration file EIO.cfg cannot be found in domain EIO.`
And the backup won't load. I don't want to just comment lines of my program, so that it _maybe_ starts working.
Also, if I try to load the arm servers manually, there are some errors in code detected:
`Reference error(130): Reference to unknown procedure g_GripIn.`
The rest of the gipper values are also underlined as errors.
I've noticed that these values are declared in MMC.cfg file, but I don't know how to load/set it up without restoring the backup.
Any help would be appreciated.
EDIT: Is it possible for anyone to provide backup file in version 6.08?
EDIT2: Tried uploading the .cfg files manually, but it doesn't seem to work.

**Comment by jeffmahler** [comment]
Which version of RobotWare do you have? We only support 6.03 and 6.06. I think you will have to contact ABB about these errors as we don't actively maintain this for updated versions of RobotWare.

**Comment by Serafadam** [comment]
I downgraded the RobotWare version to 6.06.01.00, though when uploading the files via restore backup function, dialog window pops up saying that there are still version mismatches. Do I need to modify the backup file in any way? 
When I try to load cfg files manually is seems like everything went smoothly, but there doesn't seem to be any effect on system configuration (after reset).

**Comment by jeffmahler** [comment]
There is probably a version mismatch with some of the hardware. For example, your error suggests that the grippers may be a newer version than our backup file supports.

You could also try downgrading to 6.06.00. I'm not sure if that is an issue or now.

**Comment by Serafadam** [comment]
I'll try downgrading to 6.06.00. What version of grippers do you have? I currently have 3.54 installed.

**Comment by Serafadam** [comment]
Ok, so downgrading to 6.06.00 allowed me to upload the backup without problems, but I had to change the robot serial number, as well as update the controller with robot memory data (in advanced calibration menu). I think now the system is working correctly.

**Comment by jeffmahler** [comment]
Ok good to know. Sorry for the issues. Unfortunately we don't have the bandwidth to actively maintain this for all RobotWare updates from ABB. I hope you find the library useful.
