### ISSUE TITLE
Controlling YuMi by serial port

### ISSUE THREAD

**Issue by shangzhouye** [BerkeleyAutomation/yumipy#24]
Hi, thank you for sharing this great work. I'm trying to control the YuMi robot arm by a serial port. The serial port will give the information on what direction the end-effector should move and what is the velocity. What I would like to achieve is that the robotic arm will keep moving in a certain direction and velocity until the serial command changes. For example, if the serial port tells the robotic arm to move at velocity 1 in the x-direction, the robotics will not stop until the serial port changes the velocity to 0. However, by using the goto_pose_delta it can only go to a certain position and cannot be interrupted by other commands. Could I ask is my goal feasible or is there a possible way to achieve this? Thank you.

**Comment by jeffmahler** [comment]
@shangzhouye Sorry but this is not supported in yumipy. You may be able to implement this in RAPID, in which case you could modify the server to accept commands for this functionality.

**Comment by shangzhouye** [comment]
Thank you for your reply. Also, could I ask when I use the goto_pose_delta function to rotate the end-effector, is there a specific axis it is rotation around, or it can only guarantee what orientation the end-effector is facing?
