### ISSUE TITLE
Access Yumi States from yumipy

### ISSUE THREAD

**Issue by neubotech** [BerkeleyAutomation/yumipy#3]
I couldn't seem to get the logs (robot states) message via yumipy.  Is there some other dependencies that we need in order to access those messages, say in ros-topics or rviz.

**Comment by jacky-liang** [comment]
There are two ways to get robot states or poses. If you have a YuMiRobot object you can call its get_state or get_pose commands on the left or the right arm. You can also use YuMiSubscriber by calling its get_state or get_pose on the left and right arm. YuMiSubscriber can be used even when the RAPID server is not running, which is useful for collecting state information during lead-through mode.
