### ISSUE TITLE
YuMiSubscriber failed: "connection refused"

### ISSUE THREAD

**Issue by neubotech** [BerkeleyAutomation/yumipy#5]
Hi, I'm trying to use yumi subsciber.  When I run python tools/test_subscriber.py, I got below error: 

> > Process left_poses:
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
>     self.run()
>   File "build/bdist.linux-x86_64/egg/yumipy/yumi_subscriber.py", line 42, in run
>     self._reset_socket()
>   File "build/bdist.linux-x86_64/egg/yumipy/yumi_subscriber.py", line 92, in _reset_socket
>     self._socket.connect((self._ip, self._port))
>   File "/usr/lib/python2.7/socket.py", line 224, in meth
>     return getattr(self._sock,name)(*args)
> error: [Errno 111] Connection refused

Attached the full error from running the file.  I'm wondering if I have setup the logger ip the right way?  Thanks!

Nan
[subscriber_error.txt](https://github.com/BerkeleyAutomation/yumipy/files/1167045/subscriber_error.txt)

**Comment by jacky-liang** [comment]
This can happen when the logger tasks on YuMi is not running correctly. Can you verify that they're set as semi-static, or if they're normal, are the tasks running?

The IP should be the same for all YuMi's, and if YuMiRobot class works, then YuMiSubscriber should also work as far as network settings are concerned b/c they use the same IP address in yumi_constants.py 

You can also try to instantiate YuMiSubscriber to only subscribe to poses and states and see if that work as looking at your trace the torque logger is the one that's erroring out (but torque logger by default is the first one to be connected, so doing this might not help that much):

`sub = YuMiSubscriber(left_includes=('states', 'poses'), right_includes=('states', 'poses'))`

**Comment by neubotech** [comment]
Thanks!

I find a bug in the current RAPID code.  The mod files of the loggers do not have their corresponding ports specified, so the ports uses the default number 0 from assigned persistent variable.  I added a local variable to each of the mod files, and would be able to monitor "torque", "state", and "pose".

**Comment by jacky-liang** [comment]
The ports should be specified in [Constants.mod](https://github.com/BerkeleyAutomation/yumipy/blob/master/RAPID/Constants.mod), which shares its persistent variables with the logger modules. Could you verify the Constants module is setup correctly? It'd need to be running as a semi-static task. See screenshot in [Issue 4](https://github.com/BerkeleyAutomation/yumipy/issues/4)

**Comment by neubotech** [comment]
Constant.mod was setup correctly.  But I only see port variable defined for "PORT_LOGGER_*", and the port assignments are different from what's defined in "__init__.py". I searched around and couldn't find other places in rapid to bind IP to all the logger ports.  Maybe I missed something?

**Comment by jacky-liang** [comment]
Ah thanks for pointing that out - Constants.mod hasn't been updated to the newest version in the backup. Will fix soon.
