### ISSUE TITLE
roslaunch yumipy yumi_arms.launch issue

### ISSUE THREAD

**Issue by TAS104** [BerkeleyAutomation/yumipy#6]
Hello,

I have been having an issue connecting to the YuMi robot with the YuMipy package. The package appears to be have been installed correctly with autolab in a ROS Jade catkin workspace and the server nodes are running on the flexpendant. However when the PC is connected to the service port of the robot via Ethernet cable and the command roslaunch yumipy yumi_arms.launch is executed from within the catkin workspace, the following response and error messages occur:

... logging to /home/ezzdtb/.ros/log/9c1eacd6-7379-11e7-a61e-54ee7501cfc6/roslaunch-LEZN04907-3300.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://LEZN04907:40917/

SUMMARY
========

PARAMETERS
 * /rosdistro: jade
 * /rosversion: 1.11.21
 * /yumi_robot/left_arm/display_output: True
 * /yumi_robot/left_arm/name: left
 * /yumi_robot/right_arm/display_output: True
 * /yumi_robot/right_arm/name: right

NODES
  /yumi_robot/
    left_arm (yumipy/yumi_arm_service.py)
    right_arm (yumipy/yumi_arm_service.py)

auto-starting new master
process[master]: started with pid [3312]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 9c1eacd6-7379-11e7-a61e-54ee7501cfc6
process[rosout-1]: started with pid [3325]
started core service [/rosout]
process[yumi_robot/left_arm-2]: started with pid [3328]
process[yumi_robot/right_arm-3]: started with pid [3329]
Traceback (most recent call last):
  File "/home/ezzdtb/YuMi_ws_jade/src/yumipy/ros_nodes/yumi_arm_service.py", line 11, in <module>
Traceback (most recent call last):
      File "/home/ezzdtb/YuMi_ws_jade/src/yumipy/ros_nodes/yumi_arm_service.py", line 11, in <module>
raise RuntimeError("yumi_ros_service unavailable outside of catkin package")
    raise RuntimeError("yumi_ros_service unavailable outside of catkin package")
RuntimeError: yumi_ros_service unavailable outside of catkin package
RuntimeError: yumi_ros_service unavailable outside of catkin package
[yumi_robot/left_arm-2] process has died [pid 3328, exit code 1, cmd /home/ezzdtb/YuMi_ws_jade/src/yumipy/ros_nodes/yumi_arm_service.py __name:=left_arm __log:=/home/ezzdtb/.ros/log/9c1eacd6-7379-11e7-a61e-54ee7501cfc6/yumi_robot-left_arm-2.log].
log file: /home/ezzdtb/.ros/log/9c1eacd6-7379-11e7-a61e-54ee7501cfc6/yumi_robot-left_arm-2*.log
[yumi_robot/right_arm-3] process has died [pid 3329, exit code 1, cmd /home/ezzdtb/YuMi_ws_jade/src/yumipy/ros_nodes/yumi_arm_service.py __name:=right_arm __log:=/home/ezzdtb/.ros/log/9c1eacd6-7379-11e7-a61e-54ee7501cfc6/yumi_robot-right_arm-3.log].
log file: /home/ezzdtb/.ros/log/9c1eacd6-7379-11e7-a61e-54ee7501cfc6/yumi_robot-right_arm-3*.log

Is there any solution you can recommend to resolve this error?

Kind Regards
Thomas

**Comment by 01halibut** [comment]
Apologies for the late reply.

Looks like either yumi_arm or the service definition is failing to import. Could you try just opening a python console and running

`from yumipy.yumi_arm import *`
`from yumipy.srv import *`

One of these two should fail, and that stack trace should give a better idea of what's happening.

**Comment by TAS104** [comment]
Hi,

I created a test ROS package with a python script containing the commands in and ran one at a time whilst commenting the other out. I tried this on the PC I was using and did not have the robot connected, these are the error messages that I got by running each command:

for _from yumipy.yumi_arm import *_

error is: 

ezzdtb@LEZN04907:~/YuMi_ws_jade$ rosrun test test2.py
Unable to import DataStreamSyncer and Recorder! Likely due to missing multiprocess
Traceback (most recent call last):
  File "/home/ezzdtb/YuMi_ws_jade/src/test/src/test2.py", line 3, in <module>
    from yumipy.yumi_arm import *
  File "/home/ezzdtb/YuMi_ws_jade/devel/lib/python2.7/dist-packages/yumipy/__init__.py", line 35, in <module>
    exec(__fh.read())
  File "<string>", line 8, in <module>
  File "/home/ezzdtb/YuMi_ws_jade/src/yumipy/./yumipy/yumi_planner.py", line 5, in <module>
    import IPython
ImportError: No module named IPython

for _from yumipy.srv import *_

error is:

ezzdtb@LEZN04907:~/YuMi_ws_jade$ rosrun test test2.py
Unable to import DataStreamSyncer and Recorder! Likely due to missing multiprocess
Traceback (most recent call last):
  File "/home/ezzdtb/YuMi_ws_jade/src/test/src/test2.py", line 4, in <module>
    from yumipy.srv import *
  File "/home/ezzdtb/YuMi_ws_jade/devel/lib/python2.7/dist-packages/yumipy/__init__.py", line 35, in <module>
    exec(__fh.read())
  File "<string>", line 8, in <module>
  File "/home/ezzdtb/YuMi_ws_jade/src/yumipy/./yumipy/yumi_planner.py", line 5, in <module>
    import IPython
ImportError: No module named IPython

It seems that with either of the commands that a module named IPython is missing.

**Comment by 01halibut** [comment]
Yeah looks like you need to install iPython.

Just pip install iPython and that error should go away.

**Comment by 7huan** [comment]
Hello,
I need to use it in Window10, what can I do for it?

**Comment by MERYEMTAGH** [comment]
I have the same problem and I don't know what to do.
 I installed iPython but without success do you have a proposal?
