### ISSUE TITLE
get_pose() function problem

### ISSUE THREAD

**Issue by Waynehjy** [BerkeleyAutomation/yumipy#9]
I have a problem about get_pose() . Does anyone know how to use the value I get from this function. I 
 will get Tra: , Rot: , Qtn:   The type of this function is core.rigidtransform....... , so I can't use the value I get   for doing some calculate. Hope someone can help me to solve this problem. Thanks a lot!!

**Comment by jeffmahler** [comment]
Can you provide any more details about your problem? What are you trying to do?

[Here](https://berkeleyautomation.github.io/autolab_core/api/rigid_transform.html) is an API reference for autolab_core.RigidTransform. You can get the translation and rotation specifying the 6 degrees of freedom for the state of a rigid body in 3D. For example:
`pose = RigidTransform(from_frame='gripper', to_frame='base')`
`pose.translation # numpy 3-vector for the gripper center with respect to the robot base`
`pose.quaternion # numpy 4-vector for the gripper orientation with respect to the robot base specified as a WXYZ quaternion`
`pose.rotation # numpy 3x3 orthonormal matrix with determinant 1 that specifies the gripper orientation with respect to the robot base`

**Comment by Waynehjy** [comment]
If I use get_pose() function , I can get the value from the picture show 
![001](https://user-images.githubusercontent.com/32330733/30948440-86a66232-a442-11e7-8301-5dce081fec6c.jpg)
I am trying the use the value about Tra , Rot , Qtn , but I have no idea how to save the value in a variable .This is my problem.
BTW ,for some reason I didn't install ROS. I'm not sure if it's possible to use complete function without install ROS.

**Comment by jacky-liang** [comment]
Per Jeff's response above, you can do:

```
pose = yumi.left.get_pose()
tra = pose.translation
rot = pose.rotation
qtn = pose.quaternion
```

YuMiPy can operate w/o ROS, so that's fine.
